// Code generated by girgen. DO NOT EDIT.

package spelling

// #include <stdlib.h>
// #include <libspelling.h>
import "C"

// Init: call this function before using any other libspelling functions in your
// applications. It will initialize everything needed to operate the library.
func Init() {
	C.spelling_init()
}
