// Code generated by girgen. DO NOT EDIT.

package spelling

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: libspelling-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <libspelling.h>
import "C"
